image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt
  - python setup.py install

stages:
  - Testing

black:
  stage: Testing
  script:
  - black src/malvm

flake8:
  stage: Testing
  script:
    - flake8 src/malvm

pylint:
  stage: Testing
  script:
    - pylint src/malvm

mypy:
  stage: Testing
  script:
    - mypy src/malvm

pytest:
  stage: Testing
  script:
    - pytest tests