image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Code Quality

black:
  stage: Code Quality
  script:
  - black src/malvm

flake8:
  stage: Code Quality
  script:
    - flake8 src/malvm

pylint:
  stage: Code Quality
  script:
    - pylint src/malvm

mypy:
  stage: Code Quality
  script:
    - mypy src/malvm

isort:
  stage: Code Quality
  script:
    - isort --recursive src/malvm
    - isort --recursive tests
