image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt
  - python setup.py install

stages:
  - Testing
  - Deploy

black:
  stage: Testing
  script:
  - black src/malvm

flake8:
  stage: Testing
  script:
    - flake8 src/malvm

pylint:
  stage: Testing
  script:
    - pylint src/malvm

mypy:
  stage: Testing
  script:
    - mypy src/malvm

pytest:
  stage: Testing
  script:
    - pytest tests

push-gitlab-pypi:
  stage: Deploy
  script:
   - pip install twine
   - python setup.py sdist bdist_wheel
   - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - tags