Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 4
    end
    config.vm.box = "gusztavvargadr/windows-10"
    config.vm.hostname = "Workstation"
    config.vm.provision "shell", inline: "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
    config.vm.provision "shell", inline: "choco install -y python3"
    config.vm.provision "file", source: "~/../", destination: "$HOME/malvm"
  end

